/* ---------------- data ---------------- */
const categories = [
  {key:'all', label:'All Work', color:'#e7b85c'},
  {key:'web', label:'Websites', mono:'WB', color:'#e7b85c'},
  {key:'video', label:'Video Editing', mono:'VE', color:'#ff6b57'},
  {key:'chrome', label:'Chrome Extensions', mono:'CE', color:'#4285f4'},
  {key:'firefox', label:'Firefox Extensions', mono:'FE', color:'#ff7a3d'},
  {key:'safari', label:'Safari Extensions', mono:'SE', color:'#5c7cfa'},
  {key:'wordpress', label:'WordPress Plugins', mono:'WP', color:'#9c6ade'},
  {key:'android', label:'Android Apps', mono:'AN', color:'#3ed598'},
  {key:'ios', label:'iOS Apps', mono:'IO', color:'#c9cdd3'},
  {key:'windows', label:'Windows Apps', mono:'WN', color:'#00b4d8'},
  {key:'mac', label:'Mac Apps', mono:'MC', color:'#a9adb3'},
  {key:'androidgames', label:'Android Games', mono:'AG', color:'#b5ff3d'},
  {key:'iosgames', label:'iOS Games', mono:'IG', color:'#ff3d9a'},
];
const catMap = Object.fromEntries(categories.map(c => [c.key, c]));
function slugFor(p){ return p.title.toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,16) || 'demo'; }

const projects = [
// Websites (30)
{cat:'web',title:'Verano Studio',desc:'Fashion label site with a cinematic full-bleed lookbook scroll.'},
{cat:'web',title:'Nordlys Architecture',desc:'Nordic architecture portfolio with parallax project reveals.'},
{cat:'web',title:'Kettle & Ash',desc:'Craft coffee roastery store with a brew-guide storytelling flow.'},
{cat:'web',title:'Aether Labs',desc:'Deep-tech startup site built around a WebGL particle hero.'},
{cat:'web',title:'Marrow Studio',desc:'Tattoo collective booking site with a grainy film aesthetic.'},
{cat:'web',title:'Fjord Capital',desc:'Venture fund site with a data-driven, filterable portfolio grid.'},
{cat:'web',title:'Hollow Point',desc:'Music producer showcase with audio-reactive visual moments.'},
{cat:'web',title:'Stonebridge Law',desc:'Law firm site with a restrained, editorial layout system.'},
{cat:'web',title:'Cinder & Co',desc:'Interior design studio with room-by-room scroll journeys.'},
{cat:'web',title:'Glasshouse Ventures',desc:'Real-estate developer site with 3D building walkthroughs.'},
{cat:'web',title:'Wax Type Foundry',desc:'Type foundry storefront selling custom display typefaces.'},
{cat:'web',title:'Nomad Supply Co',desc:'Outdoor gear brand with trail-mapped product storytelling.'},
{cat:'web',title:'Sable & Stone',desc:'Jewelry brand site built around macro product photography.'},
{cat:'web',title:'Halcyon Health',desc:'Wellness clinic booking site with calm, deliberate motion design.'},
{cat:'web',title:'Driftwood Films',desc:'Documentary studio reel site with a fullscreen video hero.'},
{cat:'web',title:'Ironclad Fitness',desc:'Gym membership site driven by kinetic typography.'},
{cat:'web',title:'Paperplane Agency',desc:'Creative agency site built around deep case-study pages.'},
{cat:'web',title:'Salt & Cedar',desc:'Restaurant site with a tasting-menu scroll experience.'},
{cat:'web',title:'Northline Robotics',desc:'Industrial robotics site with an interactive spec visualizer.'},
{cat:'web',title:'Cast Iron Coffee',desc:'Multi-location café finder with live map integration.'},
{cat:'web',title:'Lumen Optics',desc:'Eyewear brand site with a try-before-you-buy AR teaser.'},
{cat:'web',title:'Terra Nova Farms',desc:'Regenerative farm brand built on seasonal storytelling.'},
{cat:'web',title:'Vantage Point Realty',desc:'Property listing site with cinematic drone-footage heroes.'},
{cat:'web',title:'Static Motion',desc:'Motion design studio reel with looping fullscreen showreels.'},
{cat:'web',title:'Basalt Skincare',desc:'Skincare brand site with an ingredient-origin scroll story.'},
{cat:'web',title:'The Quiet Room',desc:'Meditation app landing page with ambient soundscape cues.'},
{cat:'web',title:'Foundry Bike Co',desc:'Custom bicycle builder with a live configurator microsite.'},
{cat:'web',title:'Marlow & Finch',desc:'Independent bookshop site with reading-list curation features.'},
{cat:'web',title:'Solstice Energy',desc:'Solar startup site with live impact-metric dashboards.'},
{cat:'web',title:'Blackletter Press',desc:'Independent publisher site with typographic book reveals.'},
// Video editing (18)
{cat:'video',title:'"Afterglow"',desc:'Wedding highlight reel with a warm, film-grain color grade.'},
{cat:'video',title:'"Concrete Bloom"',desc:'Brand documentary edit for an urban farming startup.'},
{cat:'video',title:'"Nightline"',desc:'Music video edit built on beat-synced glitch transitions.'},
{cat:'video',title:'"First Light"',desc:'12-episode travel vlog series edit shot across Iceland.'},
{cat:'video',title:'"Product Drop"',desc:'30-second launch trailer for a limited sneaker release.'},
{cat:'video',title:'"Static Hours"',desc:'Short film edit built around a nonlinear flashback structure.'},
{cat:'video',title:'"Field Notes"',desc:'Nature documentary edit with slow, ambient pacing.'},
{cat:'video',title:'"Overdrive"',desc:'Automotive commercial cut with high-speed match cuts.'},
{cat:'video',title:'"The Standup"',desc:'Comedy special edit with punch-in crowd reaction cuts.'},
{cat:'video',title:'"Skyline Reel"',desc:'Cinematic real-estate tour, drone-to-interior transitions.'},
{cat:'video',title:'"Founders"',desc:'Startup pitch video series mixing talking-head and b-roll.'},
{cat:'video',title:'"Afterparty"',desc:'Event recap edit produced for a music festival client.'},
{cat:'video',title:'"Quiet Hands"',desc:'Craft-maker mini-documentary built around macro b-roll.'},
{cat:'video',title:'"Payload"',desc:'Gaming montage edit with kinetic HUD-style overlays.'},
{cat:'video',title:'"Runway"',desc:'Fashion show recap edit cutting runway to backstage.'},
{cat:'video',title:'"Home Cooked"',desc:'Recipe video series edited with top-down cutting shots.'},
{cat:'video',title:'"Signal"',desc:'Corporate explainer edit with animated data overlays.'},
{cat:'video',title:'"Low Tide"',desc:'Surf brand short film built on slow-motion wave sequences.'},
// Chrome extensions (16)
{cat:'chrome',title:'TabTether',desc:'Groups and syncs related tabs across windows automatically.'},
{cat:'chrome',title:'QuoteCatcher',desc:'Highlights page text and saves quotes to a sidebar library.'},
{cat:'chrome',title:'FocusFrame',desc:'Blocks distracting sites during timed deep-work sessions.'},
{cat:'chrome',title:'PriceEcho',desc:'Tracks product prices and alerts you the moment they drop.'},
{cat:'chrome',title:'ReadRail',desc:'Strips page clutter for a clean, focused reading view.'},
{cat:'chrome',title:'ColorSnap',desc:'Picks and copies exact colors from any webpage.'},
{cat:'chrome',title:'LinkVault',desc:'Saves links into searchable, tagged collections.'},
{cat:'chrome',title:'GridSnap',desc:'Snaps browser windows into custom tiled layouts.'},
{cat:'chrome',title:'FontFinder',desc:'Identifies every font used on the current page instantly.'},
{cat:'chrome',title:'TabTimer',desc:'Shows exactly how long each open tab has sat idle.'},
{cat:'chrome',title:'MetaPeek',desc:'Inspects a page\'s SEO tags and metadata at a glance.'},
{cat:'chrome',title:'ClipQueue',desc:'Queues copied snippets into a running clipboard list.'},
{cat:'chrome',title:'NightPane',desc:'Applies a smart, readable dark mode to any website.'},
{cat:'chrome',title:'FormFill Pro',desc:'Fills repetitive forms instantly from saved templates.'},
{cat:'chrome',title:'ScreenSlice',desc:'Captures full-page scrolling screenshots in one click.'},
{cat:'chrome',title:'WordCountr',desc:'Live word count and reading-time estimate for any page.'},
// Firefox extensions (16)
{cat:'firefox',title:'TabHarbor',desc:'Archives inactive tabs into a searchable harbor list.'},
{cat:'firefox',title:'PrivacyLatch',desc:'One-click toggle for tracker and fingerprint blocking.'},
{cat:'firefox',title:'ReaderTone',desc:'Adjusts article contrast and warmth for easier reading.'},
{cat:'firefox',title:'BookmarkBloom',desc:'Visual, board-style organizer for saved bookmarks.'},
{cat:'firefox',title:'SessionKeeper',desc:'Saves and restores complete browsing sessions on demand.'},
{cat:'firefox',title:'InkNote',desc:'Sticky notes pinned directly to specific web pages.'},
{cat:'firefox',title:'SpeedTrim',desc:'Trims autoplay video and ad payloads for faster loads.'},
{cat:'firefox',title:'ContainerFlow',desc:'Manages multi-account containers with quick switching.'},
{cat:'firefox',title:'GlyphGrab',desc:'Extracts and copies icon assets straight from any page.'},
{cat:'firefox',title:'HistoryMap',desc:'Visualizes browsing history as a connected timeline.'},
{cat:'firefox',title:'QuietTabs',desc:'Mutes newly opened tabs by default until focused.'},
{cat:'firefox',title:'CiteRight',desc:'Generates ready-to-use citations from the current page.'},
{cat:'firefox',title:'PixelRuler',desc:'On-screen ruler and ratio guide built for designers.'},
{cat:'firefox',title:'FeedStream',desc:'Lightweight RSS reader panel built into the browser.'},
{cat:'firefox',title:'TypoSpot',desc:'Flags common typos while browsing and drafting text.'},
{cat:'firefox',title:'ArchiveNow',desc:'Sends the current page straight to a public web archive.'},
// Safari extensions (16)
{cat:'safari',title:'TabCompass',desc:'Minimal tab search built for trackpad-first gestures.'},
{cat:'safari',title:'ReadPane',desc:'Distraction-free reading mode tuned for macOS typography.'},
{cat:'safari',title:'HandoffTabs',desc:'Sends open tabs between Mac and iPhone instantly.'},
{cat:'safari',title:'ColorLift',desc:'Extracts a usable color palette from any page\'s imagery.'},
{cat:'safari',title:'QuietScroll',desc:'Smooths and calms scroll momentum on busy pages.'},
{cat:'safari',title:'LinkLatch',desc:'Long-press to preview links without leaving the page.'},
{cat:'safari',title:'FocusVeil',desc:'Dims everything on the page but the active reading column.'},
{cat:'safari',title:'ClipToNotes',desc:'Sends selected web text directly into Apple Notes.'},
{cat:'safari',title:'TrackOff',desc:'Lightweight tracker blocking designed to save battery.'},
{cat:'safari',title:'ScreenTime+',desc:'Per-site time tracking with a weekly usage summary.'},
{cat:'safari',title:'ZoomKeeper',desc:'Remembers your preferred zoom level for every website.'},
{cat:'safari',title:'TabFolders',desc:'Organizes open tabs into collapsible folder groups.'},
{cat:'safari',title:'PastePlain',desc:'Strips formatting from anything copied off the web.'},
{cat:'safari',title:'NightShelf',desc:'Schedules dark mode automatically by sunrise and sunset.'},
{cat:'safari',title:'GestureBar',desc:'Adds customizable swipe gestures for page navigation.'},
{cat:'safari',title:'QuickTranslate',desc:'Inline translation popover for any selected text.'},
// WordPress plugins (16)
{cat:'wordpress',title:'SwiftForm Builder',desc:'Drag-and-drop form builder with conditional logic.'},
{cat:'wordpress',title:'CacheRunner',desc:'Full-page and object caching for faster load times.'},
{cat:'wordpress',title:'ReviewStack',desc:'Collects and displays structured, filterable product reviews.'},
{cat:'wordpress',title:'SeoPilot',desc:'On-page SEO scoring with clear, actionable fixes.'},
{cat:'wordpress',title:'BookingDesk',desc:'Appointment and resource booking calendar system.'},
{cat:'wordpress',title:'GalleryLoom',desc:'Masonry and lightbox galleries with lazy loading.'},
{cat:'wordpress',title:'MailBridge',desc:'Connects WordPress forms to major email platforms.'},
{cat:'wordpress',title:'MembershipGate',desc:'Paywalled content with tiered membership access.'},
{cat:'wordpress',title:'SpeedTrim WP',desc:'Automatic image compression and lazy-load setup.'},
{cat:'wordpress',title:'BackupVault',desc:'Scheduled, incremental site backups to cloud storage.'},
{cat:'wordpress',title:'PopupCraft',desc:'Timed and scroll-triggered popups and promo banners.'},
{cat:'wordpress',title:'TableForge',desc:'Sortable, filterable data tables from CSV or Sheets.'},
{cat:'wordpress',title:'ShopSync',desc:'Syncs WooCommerce inventory across marketplaces.'},
{cat:'wordpress',title:'CommentGuard',desc:'Spam filtering with a clean comment moderation queue.'},
{cat:'wordpress',title:'RedirectMap',desc:'Bulk 404 detection and redirect management dashboard.'},
{cat:'wordpress',title:'MultiLang Bridge',desc:'Page-level translation and language switching.'},
// Android apps (16)
{cat:'android',title:'Ledgerly',desc:'Personal budgeting app with envelope-style categories.'},
{cat:'android',title:'TrailMarker',desc:'Offline hiking maps with GPS breadcrumb trails.'},
{cat:'android',title:'FocusJar',desc:'Pomodoro timer with a visual jar-filling progress cue.'},
{cat:'android',title:'Pantry Ping',desc:'Tracks pantry stock and expiry-date reminders.'},
{cat:'android',title:'RideLog',desc:'Motorcycle trip logger with route and fuel-use stats.'},
{cat:'android',title:'QuietAlarm',desc:'Gradual-wake alarm clock with sleep-cycle tracking.'},
{cat:'android',title:'HabitGrid',desc:'Habit tracker built around a yearly grid heatmap.'},
{cat:'android',title:'NoteBeam',desc:'Voice-to-text notes synced across every device.'},
{cat:'android',title:'CoinKeeper',desc:'Simple expense splitter for shared households.'},
{cat:'android',title:'GardenLog',desc:'Plant care reminders with growth photo timelines.'},
{cat:'android',title:'ShiftBoard',desc:'Shift-worker scheduling with overtime calculations.'},
{cat:'android',title:'PulseCheck',desc:'Guided breathing and heart-rate check-in app.'},
{cat:'android',title:'CommuteSense',desc:'Predicts commute delays from live transit data.'},
{cat:'android',title:'RecipeBox',desc:'Offline recipe manager with pantry-based suggestions.'},
{cat:'android',title:'ScanStack',desc:'Document scanner with automatic edge detection.'},
{cat:'android',title:'WeightWatch',desc:'Minimal weight and body-metric tracking log.'},
// iOS apps (16)
{cat:'ios',title:'Driftlist',desc:'Widget-first to-do app built for the iOS home screen.'},
{cat:'ios',title:'Nightframe',desc:'Manual camera app with film-inspired presets.'},
{cat:'ios',title:'Steadyroute',desc:'Running app with pace coaching and live splits.'},
{cat:'ios',title:'Inkwell',desc:'Distraction-free journaling app with daily prompts.'},
{cat:'ios',title:'Pocket Ledger',desc:'Cash-based budgeting for iPhone and Apple Watch.'},
{cat:'ios',title:'FocusDial',desc:'Screen time coach that nudges gently, not harshly.'},
{cat:'ios',title:'Skyframe',desc:'Weather app with hyperlocal radar animation.'},
{cat:'ios',title:'HomeSort',desc:'Room-by-room home inventory and warranty tracker.'},
{cat:'ios',title:'QuietTimer',desc:'Minimal interval timer for workouts and meditation.'},
{cat:'ios',title:'Storyboard Lite',desc:'Simple shot-list and storyboard app for filmmakers.'},
{cat:'ios',title:'Tidewatch',desc:'Surf and tide forecast app for coastal spots.'},
{cat:'ios',title:'Pulseform',desc:'Heart-rate zone trainer synced with Apple Watch.'},
{cat:'ios',title:'Notekeep',desc:'Handwriting-to-text notes with Apple Pencil support.'},
{cat:'ios',title:'Fuelog',desc:'Car fuel-efficiency and maintenance tracker.'},
{cat:'ios',title:'Readloop',desc:'Reading tracker with yearly stats and streaks.'},
{cat:'ios',title:'Petframe',desc:'Pet health, vaccine, and vet-visit tracker.'},
// Windows apps (16)
{cat:'windows',title:'TaskDock',desc:'Floating always-on-top to-do widget for the desktop.'},
{cat:'windows',title:'ClipVault',desc:'Persistent clipboard history manager with instant search.'},
{cat:'windows',title:'WinTidy',desc:'One-click desktop and downloads folder organizer.'},
{cat:'windows',title:'BatteryWatch',desc:'Battery health monitor for laptops with smart alerts.'},
{cat:'windows',title:'QuickRename',desc:'Bulk file renaming driven by simple pattern rules.'},
{cat:'windows',title:'ScreenTimeDesk',desc:'Application usage tracker built for focus insights.'},
{cat:'windows',title:'StartupTrim',desc:'Manages and audits startup program performance impact.'},
{cat:'windows',title:'NoteDock',desc:'Sticky notes with markdown support and reminders.'},
{cat:'windows',title:'FileSentry',desc:'Watches folders and auto-sorts new downloads.'},
{cat:'windows',title:'WinCast',desc:'Local screen recording with lightweight overlays.'},
{cat:'windows',title:'HotkeyForge',desc:'Custom global hotkey and macro builder.'},
{cat:'windows',title:'NetPulse',desc:'Real-time bandwidth monitor broken down per app.'},
{cat:'windows',title:'PrintQueue+',desc:'Simplified print job manager for shared printers.'},
{cat:'windows',title:'BackupLoop',desc:'Scheduled folder backups to external or cloud drives.'},
{cat:'windows',title:'WinDim',desc:'Automatic blue-light and brightness scheduling.'},
{cat:'windows',title:'AppLock',desc:'Password-locks selected apps and folders.'},
// Mac apps (16)
{cat:'mac',title:'MenuBar Ledger',desc:'Quick expense entry straight from the macOS menu bar.'},
{cat:'mac',title:'Focusbar',desc:'Menu-bar Pomodoro timer synced with do-not-disturb.'},
{cat:'mac',title:'DiskSweep',desc:'Visual disk-space analyzer and one-click cleanup tool.'},
{cat:'mac',title:'ClipboardStack',desc:'Menu-bar clipboard history with pinned favorites.'},
{cat:'mac',title:'WindowSnap',desc:'Keyboard-driven window tiling and snapping.'},
{cat:'mac',title:'BatteryBar',desc:'Menu-bar battery health and cycle-count monitor.'},
{cat:'mac',title:'QuietDock',desc:'Auto-hides dock icons based on the active app.'},
{cat:'mac',title:'ScreenTimeBar',desc:'Lightweight app-usage tracker in the menu bar.'},
{cat:'mac',title:'NoteFloat',desc:'Always-on-top floating sticky notes for quick capture.'},
{cat:'mac',title:'RenameForge',desc:'Batch file renaming with a live preview pane.'},
{cat:'mac',title:'MailTriage',desc:'Menu-bar inbox triage for fast zero-inbox sweeps.'},
{cat:'mac',title:'FontBar',desc:'Quick font preview and installer from the menu bar.'},
{cat:'mac',title:'NetGauge',desc:'Per-app network usage graphs in real time.'},
{cat:'mac',title:'Wallpaperly',desc:'Scheduled wallpaper rotation from local folders.'},
{cat:'mac',title:'HandoffNotes',desc:'Syncs quick notes instantly between Mac and iPhone.'},
{cat:'mac',title:'SleepGuard',desc:'Prevents accidental sleep during long-running tasks.'},
// Android games (16)
{cat:'androidgames',title:'Neon Drift',desc:'Arcade racer dodging traffic through a neon-lit city.'},
{cat:'androidgames',title:'Block Cascade',desc:'Falling-block puzzle with combo chain scoring.'},
{cat:'androidgames',title:'Pixel Raiders',desc:'Retro top-down dungeon crawler with permadeath runs.'},
{cat:'androidgames',title:'Tiny Kingdoms',desc:'Idle city-builder with offline progress rewards.'},
{cat:'androidgames',title:'Reflex Rings',desc:'Fast-paced tap-timing arcade challenge.'},
{cat:'androidgames',title:'Orbit Smash',desc:'Physics-based planet-smashing puzzle game.'},
{cat:'androidgames',title:'Word Drift',desc:'Falling-letter word puzzle against the clock.'},
{cat:'androidgames',title:'Shadow Runner',desc:'Endless runner through a constantly shifting shadow world.'},
{cat:'androidgames',title:'Colony Tap',desc:'Idle ant-colony builder with layered resource chains.'},
{cat:'androidgames',title:'Puzzle Forge',desc:'Match-3 puzzler with a blacksmithing crafting twist.'},
{cat:'androidgames',title:'Skybound Racers',desc:'Airborne obstacle racer with drift-boost mechanics.'},
{cat:'androidgames',title:'Memory Vault',desc:'Card-matching puzzle with escalating difficulty tiers.'},
{cat:'androidgames',title:'Tap Legends',desc:'Idle RPG battler driven by tap-to-attack combat.'},
{cat:'androidgames',title:'Gravity Maze',desc:'Tilt-based ball-rolling maze puzzler.'},
{cat:'androidgames',title:'Rush Hour Riot',desc:'Traffic-jam sliding puzzle game across 80 levels.'},
{cat:'androidgames',title:'Farmstead Frenzy',desc:'Time-management farming arcade game.'},
// iOS games (16)
{cat:'iosgames',title:'Driftline',desc:'Minimalist one-tap endless runner.'},
{cat:'iosgames',title:'Cascade Blocks',desc:'Satisfying falling-block puzzle built for quick sessions.'},
{cat:'iosgames',title:'Lumen Maze',desc:'Light-guided maze puzzler with 100 handcrafted levels.'},
{cat:'iosgames',title:'Starforge Idle',desc:'Idle spaceship-building incremental game.'},
{cat:'iosgames',title:'Tap Duel',desc:'Local two-player reflex tapping showdown.'},
{cat:'iosgames',title:'Glyph Match',desc:'Symbol-matching puzzle with rotating daily challenges.'},
{cat:'iosgames',title:'Wavelength',desc:'Rhythm-tap game synced to original tracks.'},
{cat:'iosgames',title:'Orbit Runner',desc:'Gravity-based endless orbit-jumping arcade game.'},
{cat:'iosgames',title:'Petal Drift',desc:'Calm, meditative falling-petal puzzle game.'},
{cat:'iosgames',title:'Vault Breaker',desc:'Safe-cracking puzzle game with rotating dial mechanics.'},
{cat:'iosgames',title:'Skyline Jumpers',desc:'Rooftop-hopping endless runner.'},
{cat:'iosgames',title:'Chroma Snap',desc:'Color-matching reflex arcade game.'},
{cat:'iosgames',title:'Puzzle Loop',desc:'Pipe-connecting logic puzzle across 150 levels.'},
{cat:'iosgames',title:'Nightfall Dash',desc:'Dark-themed obstacle dash with score multipliers.'},
{cat:'iosgames',title:'Memory Peaks',desc:'Mountain-themed card memory challenge.'},
{cat:'iosgames',title:'Idle Aquarium',desc:'Relaxing incremental fish-tank builder.'},
];

// index within category, for the mono readout
const catCounters = {};
projects.forEach((p,i) => {
  catCounters[p.cat] = (catCounters[p.cat]||0)+1;
  p.idx = catCounters[p.cat];
  p.id = i;
});

const experience = [
  {date:'2024 — Present', role:'Founder & Independent Builder, Bazozo', desc:'Running a solo studio covering web design/dev, video editing, browser & WordPress extensions, and native apps across Android, iOS, Windows and macOS for direct clients worldwide.'},
  {date:'2022 — 2024', role:'Frontend Engineer (Contract)', desc:'Built and maintained marketing sites and internal tools for agency clients, focused on animation-heavy, high-conversion landing pages.'},
  {date:'2020 — 2022', role:'Junior Web Developer', desc:'Started out shipping WordPress sites and small e-commerce builds, then moved into custom front-end work as skills grew.'},
  {date:'2019 — 2020', role:'Freelance Video Editor & Motion Designer', desc:'Edited social and brand video for small businesses and creators, picking up motion design and color grading along the way.'},
];

const crafts = [
  {name:'Web Design & Dev', sub:'Marketing sites, web apps, e-commerce', key:'web'},
  {name:'Video Editing', sub:'Brand films, socials, documentaries', key:'video'},
  {name:'Chrome Extensions', sub:'Productivity & browser tooling', key:'chrome'},
  {name:'Firefox Extensions', sub:'Privacy, reading & tab tools', key:'firefox'},
  {name:'Safari Extensions', sub:'macOS & iOS-native browser tools', key:'safari'},
  {name:'WordPress Plugins', sub:'Forms, commerce, performance', key:'wordpress'},
  {name:'Android Apps', sub:'Native Kotlin/Java applications', key:'android'},
  {name:'iOS Apps', sub:'Native Swift/SwiftUI applications', key:'ios'},
  {name:'Windows Apps', sub:'Native desktop utilities', key:'windows'},
  {name:'Mac Apps', sub:'Menu-bar tools & native utilities', key:'mac'},
  {name:'Android Games', sub:'Casual to arcade, built native', key:'androidgames'},
  {name:'iOS Games', sub:'Casual to arcade, built native', key:'iosgames'},
];

const services = [
  {title:'SEO & Technical SEO', desc:'Audits, on-page optimization, and structured data that get sites found.'},
  {title:'Website Migration', desc:'Domain, host, or platform moves planned for zero downtime.'},
  {title:'Website Redesign', desc:'Modernizing outdated sites without losing search rankings.'},
  {title:'Performance Optimization', desc:'Core Web Vitals, load-time, and asset-weight audits and fixes.'},
  {title:'E-commerce Development', desc:'Product catalogs, checkout flows, and payment integration.'},
  {title:'CMS Development', desc:'WordPress, headless CMS, and custom admin panels.'},
  {title:'Landing Page Design', desc:'High-conversion single-page campaigns for launches and ads.'},
  {title:'UI/UX Design', desc:'Wireframes, prototypes, and reusable design systems.'},
  {title:'Web App Development', desc:'Dashboards, internal tools, and SaaS product builds.'},
  {title:'API Integration', desc:'Connecting payment gateways, CRMs, and third-party services.'},
  {title:'Progressive Web Apps', desc:'Installable, offline-capable experiences from a single codebase.'},
  {title:'Accessibility Audits', desc:'WCAG compliance reviews with concrete, prioritized fixes.'},
  {title:'Security Hardening', desc:'SSL setup, header hardening, and malware cleanup.'},
  {title:'Analytics & Tracking', desc:'GA4, GTM, and conversion/event tracking implementation.'},
  {title:'Conversion Rate Optimization', desc:'A/B testing and funnel improvements based on real data.'},
  {title:'Hosting & Domain Setup', desc:'DNS, email routing, and server configuration done right.'},
  {title:'Website Maintenance', desc:'Ongoing updates, backups, and uptime monitoring.'},
  {title:'Multilingual Localization', desc:'Multi-language, region-targeted site builds.'},
  {title:'Legacy System Modernization', desc:'Rebuilding outdated codebases on modern foundations.'},
  {title:'Speed & SEO Audits', desc:'Full technical reports with clearly prioritized next steps.'},
];
